name: Playwright E2E Testing
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - name: Install Playwright
        run: npx playwright install-deps chromium
      - name: Install Deps
        run: yarn
      - name: Build App
        run: yarn build
      - name: Start App
        run: yarn start &
      - name: Run Test
        run: yarn test:e2e
