name: Playwright E2E Testing
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - name: Start App
        run: |
          npx playwright install-deps chromium
          yarn
          yarn build
          yarn start &
      - name: Run Test
        run: yarn test:e2e
        with:
          wait-on: "http://localhost:3000"
